[book]
title = "Kubernetes through Incidents and Stories"
language = "en"
src = "src"

[output.html]
git-repository-url = ""
print = { enable = true }
additional-css = ["theme/custom.css"]

[output.pdf]
